# Generated by Django 3.2 on 2023-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=111111, max_length=6, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
