# Generated by Django 3.2 on 2023-10-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_unique_username_and_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_username_and_email',
        ),
    ]
