# Generated by Django 3.2 on 2023-10-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231003_1553'),
        ('reviews', '0003_alter_review_title'),
    ]

    operations = [
    ]
