# Generated by Django 3.2 on 2023-10-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20231006_1007'),
        ('reviews', '0008_alter_title_options'),
    ]

    operations = [
    ]
