# Generated by Django 3.2 on 2023-10-07 09:35

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20231006_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.validate_year], verbose_name='Год выпуска'),
        ),
    ]
